language: node_js
node_js:
    - "0.10"

script: "npm test && npm run perf"

before_install:
    - npm link
    - cd ..
    - git clone git://github.com/eslint/eslint-tester.git
    - cd eslint-tester
    - npm link
    - npm link eslint
    - cd ../eslint
    - npm link eslint-tester
